# Generated by Django 4.2.7 on 2025-10-22 18:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=200)),
                ('cliente_telefone', models.CharField(max_length=20)),
                ('cliente_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_agendamento', models.DateField()),
                ('hora_agendamento', models.TimeField()),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('falta', 'Falta')], default='agendado', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('confirmado_whatsapp', models.BooleanField(default=False)),
                ('whatsapp_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mensagem_confirmacao', models.TextField(blank=True, null=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='servicos.profissional')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='servicos.servico')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-data_agendamento', '-hora_agendamento'],
                'unique_together': {('profissional', 'data_agendamento', 'hora_agendamento')},
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoBarbearia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_barbearia', models.CharField(default='Barbearia', max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('horario_funcionamento', models.TextField(blank=True, null=True)),
                ('whatsapp_business_id', models.CharField(blank=True, max_length=100, null=True)),
                ('token_whatsapp', models.CharField(blank=True, max_length=500, null=True)),
                ('mongo_connection_string', models.CharField(blank=True, max_length=500, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuração da Barbearia',
                'verbose_name_plural': 'Configurações da Barbearia',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(help_text='Nota de 1 a 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='agendamentos.agendamento')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data_avaliacao'],
            },
        ),
        migrations.CreateModel(
            name='HorarioDisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('intervalo_minutos', models.PositiveIntegerField(default=30, help_text='Intervalo entre agendamentos em minutos')),
                ('ativo', models.BooleanField(default=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disponibilidade', to='servicos.profissional')),
            ],
            options={
                'verbose_name': 'Horário de Disponibilidade',
                'verbose_name_plural': 'Horários de Disponibilidade',
                'ordering': ['profissional', 'dia_semana', 'hora_inicio'],
                'unique_together': {('profissional', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
